config/routes.rb
Rails.application.routes.draw do

  resources :users
  post 'logins/check' => 'logins#check'

  resources :logins

  root 'welcome#index'

end

app/models/login.rb
class Login < ActiveRecord::Base
	belongs_to :user
	validates :user_login, :password, presence: true	
	validates :password, length: { in: 5..20 }
	validates :user_login, length: { in: 3..30 }
	validates :user_login, uniqueness: { case_sensitive: false }
  
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :first_name, presence: true	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  before_filter :verify_token
  before_filter :check_login_params, only: [:create, :update, :check ]

  before_action :set_login, only: [:show, :edit, :update, :destroy ]

  protect_from_forgery with: :null_session

  # skip_before_filter :verify_authenticity_token  
  # GET /logins
  # GET /logins.json
  # curl -H "Accept: application/json" -H "Content-type: application/json" http://localhost:3000/logins.json -X GET -d '{"authenticity_token": ""}'  
  # curl -H "Accept: application/json" -H "Content-type: application/json" https://bartermd.herokuapp.com/logins.json -X GET -d '{"authenticity_token": ""}'  

  def index
    @logins = Login.all
  end

  # curl -H "Accept: application/json" -H "Content-type: application/json" http://localhost:3000/logins/14.json -X GET -d '{"authenticity_token": ""}'
  # GET /logins/1
  # GET /logins/1.json
  def show
  end

  # GET /logins/new
  def new
    @login = Login.new
  end

  # GET /logins/1/edit
  def edit
  end

  # POST /logins
  # POST /logins.json
  # curl -H "Accept: application/json" -H "Content-type: application/json" http://localhost:3000/logins.json -X POST  -d '{"authenticity_token": "", "login":{"user_login":"4442","password":"very12"}}'
  def create
    
    @login = Login.new(login_params)
    respond_to do |format|
      if @login.save
        format.html { redirect_to @login, notice: 'Login was successfully created.' }
        format.json { render :show, status: :created, location: @login }
      else
        format.html { render :new }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /logins/1
  # PATCH/PUT /logins/1.json
  # curl -H "Accept: application/json" -H "Content-type: application/json" http://localhost:3000/logins/1.json -X PUT  -d '{"authenticity_token": "", "login":{"user_login":"4442","password":"very12"}}'
  def update
    respond_to do |format|
      if @login.update(login_params)
        format.html { redirect_to @login, notice: 'Login was successfully updated.' }
        format.json { render :show, status: :ok, location: @login }
      else
        format.html { render :edit }
        format.json { render json: @login.errors, status: :unprocessable_entity }
      end
    end
  end

  # curl -H "Accept: application/json" -H "Content-type: application/json" http://localhost:3000/logins/14.json -X GET -d '{"authenticity_token": ""}'
  # GET /logins/1
  # GET /logins/1.json
  def check
    # binding.pry
    @login = Login.find_by_user_login params[:login][:user_login]
    
    unless @login
      render nothing: true, status:  404 # Not found login
      return    
    end 

    if @login.password == params[:login][:password]
      render json: @login
    else
      render nothing: true, status:  401 # Not password corespond login
    end

  end

  # DELETE /logins/1
  # DELETE /logins/1.json
  # curl -H "Accept: application/json" -H "Content-type: application/json" http://localhost:3000/logins/12.json -X DELETE -d '{"authenticity_token": ""}'

  def destroy
    
    @login.destroy
    respond_to do |format|
      format.html { redirect_to logins_url, notice: 'Login was successfully destroyed.' }
      format.json { render nothing: true, status:  200 }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_login
      if not Login.exists? params[:id]
         render nothing: true, status:  404
         return
      end           
      @login = Login.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def login_params
      params.require(:login).permit(:user_login, :password)
    end

    def check_login_params
      render nothing: true, status:  422 unless params[:login]
    end

    def verify_token
        respond_to do |format|  
          format.html {}    
          format.json do
             auth = params["authenticity_token"] == ENV['AUTH_TOKEN']
             render nothing: true, status:  403 unless auth
          end
        end
      
    end
 
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
  before_filter :verify_token  
  before_filter :check_login_params, only: [:create, :update ]  
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  protect_from_forgery with: :null_session
# skip_before_filter :verify_authenticity_token 
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create

    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy

    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { render nothing: true, status: :ok}
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      if not User.exists? params[:id]
         render nothing: true, status:  404
         return
      end           

      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :second_name, :date_bith, :photo_url, :description, :location, :phone)
    end

    def check_login_params
      render nothing: true, status:  422 unless params[:user]
    end

    def verify_token
        respond_to do |format|  
          format.html {}    
          format.json do
             auth = params["authenticity_token"] == ENV['AUTH_TOKEN']
             render nothing: true, status:  403 unless auth
          end
        end
      
    end
    
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Barter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/logins/_form.html.erb
<%= form_for(@login) do |f| %>
  <% if @login.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@login.errors.count, "error") %> prohibited this login from being saved:</h2>

      <ul>
      <% @login.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_login %><br>
    <%= f.text_field :user_login %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/logins/edit.html.erb
<h1>Editing Login</h1>

<%= render 'form' %>

<%= link_to 'Show', @login %> |
<%= link_to 'Back', logins_path %>

app/views/logins/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Logins</h1>

<table>
  <thead>
    <tr>
      <th>User login</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @logins.each do |login| %>
      <tr>
        <td><%= login.user_login %></td>
        <td><%= login.password %></td>
        <td><%= link_to 'Show', login %></td>
        <td><%= link_to 'Edit', edit_login_path(login) %></td>
        <td><%= link_to 'Destroy', login, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Login', new_login_path %>

app/views/logins/new.html.erb
<h1>New Login</h1>

<%= render 'form' %>

<%= link_to 'Back', logins_path %>

app/views/logins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User login:</strong>
  <%= @login.user_login %>
</p>

<p>
  <strong>Password:</strong>
  <%= @login.password %>
</p>

<%= link_to 'Edit', edit_login_path(@login) %> |
<%= link_to 'Back', logins_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :second_name %><br>
    <%= f.text_field :second_name %>
  </div>
  <div class="field">
    <%= f.label :date_bith %><br>
    <%= f.date_select :date_bith %>
  </div>
  <div class="field">
    <%= f.label :photo_url %><br>
    <%= f.text_field :photo_url %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Second name</th>
      <th>Date bith</th>
      <th>Photo url</th>
      <th>Description</th>
      <th>Location</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.second_name %></td>
        <td><%= user.date_bith %></td>
        <td><%= user.photo_url %></td>
        <td><%= user.description %></td>
        <td><%= user.location %></td>
        <td><%= user.phone %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @user.first_name %>
</p>

<p>
  <strong>Second name:</strong>
  <%= @user.second_name %>
</p>

<p>
  <strong>Date bith:</strong>
  <%= @user.date_bith %>
</p>

<p>
  <strong>Photo url:</strong>
  <%= @user.photo_url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @user.description %>
</p>

<p>
  <strong>Location:</strong>
  <%= @user.location %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @user.phone %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>